### ISSUE TITLE
Does python-tsic work on the RPi4?

### ISSUE THREAD

**Issue by ChasNelson1990** [grillbaer/python-tsic#2]
Hi there,

Trying to use python-tsic to read from a TSic 360. I only seem to get 'Unknown' from a measurement, even if I manually do `tsic.start()` before (and check `is_started()` before and after).

Now, one option could be an error between the soldering iron and the solder, I'm far from an expert in electronics. But I have a TO-92 format TSic 360 with ground connected to RPi4 Pin No. 9 and V+ connected to RPi4 pin No. 1 and the signal pin connected to RPi4 Pin No. 11 (GPIO 17) [I have also tried other GPIO pins]. I also have a 104 nF capacitor in parallel with the ground and V+ pins.

I have the pigpio daemon running but just seem to get no measurements - any ideas?

The only thing I can think of is that pigpio currently have a warning that their RPi4 support is experimental. Have you been able to trial python-tsic on an RPi 4 yet? Does it work?

Is there anything I need to enable in raspi-config? I know the TSic uses ZACWire, right? But I don't know anymore about that protocol than it's name.

Thanks for any help you can offer - I realise this could be as much an electronics question as a python-tsic question!

**Comment by ChasNelson1990** [comment]
I can confirm that it does work on the RPi4. I bought some new sensors (previous were an eBay find) and I think it was a hardware issue and not a software issue.

**Comment by grillbaer** [comment]
Hi @ChasNelson1990, I'm happy to hear that you already could resolve the issue. Thanks for your feedback on the final solution.
