### ISSUE TITLE
Problem reading temperature with TSIC506

### ISSUE THREAD

**Issue by y09IhqPnk** [grillbaer/python-tsic#3]
Hi,

it's not possible to use that libary with TSIC506 sensors, because there is a typo in tsic.py.
Inside the __all__ list the entry TSIC306 is dublicated and the one of TSIC506 is missing.

If one of these is changed to TSIC506, it works.

Could you please correct that in your repo?

Thanks
![tsic](https://user-images.githubusercontent.com/80919356/111682231-6505a100-8824-11eb-8b9a-6785c7c4ca96.png)

**Comment by grillbaer** [comment]
Hi, thanks for your bug report. You are right and obviously the first one to use it with a TSIC506. I'll fix that.

**Comment by grillbaer** [comment]
The bugfix version is available on pypi, now. After upgrading your package with `pip3 install --upgrade tsic` it should work.

**Comment by y09IhqPnk** [comment]
Thank you very much for your suport!
